### ISSUE TITLE
关于excavator的请教

### ISSUE THREAD

**Issue by isSmileYang** [mogoson/MGS-Machinery#1]
大神，看了您的MGS-Machinery献上膝盖~~其中挖掘机的液压缸和液压杆处脚本只看到“Rocker Joint”（摇杆关节，始终朝向目标关节。
请问除了这个脚本之外液压缸和液压杆处的运动还有用到其它的设置么，比如“configuration joint”？

**Comment by mogoson** [comment]
没有使用configuration joint；仅仅是Rocker Joint脚本控制的。
